// ISO2 country code → representative IANA timezone. Used to compute a user's
// local midnight for daily resets when they haven't set an explicit timezone.
// Multi-timezone countries (US, RU, BR, CA, AU, ID…) map to their most-populous
// zone; users in another zone can override via their profile timezone.
// Pure + client/server safe (no imports).

export const COUNTRY_TZ: Record<string, string> = {
  // South Asia
  BD: "Asia/Dhaka",
  IN: "Asia/Kolkata",
  PK: "Asia/Karachi",
  LK: "Asia/Colombo",
  NP: "Asia/Kathmandu",
  BT: "Asia/Thimphu",
  MV: "Indian/Maldives",
  AF: "Asia/Kabul",
  // Southeast / East Asia
  ID: "Asia/Jakarta",
  MY: "Asia/Kuala_Lumpur",
  SG: "Asia/Singapore",
  TH: "Asia/Bangkok",
  VN: "Asia/Ho_Chi_Minh",
  PH: "Asia/Manila",
  MM: "Asia/Yangon",
  KH: "Asia/Phnom_Penh",
  LA: "Asia/Vientiane",
  CN: "Asia/Shanghai",
  HK: "Asia/Hong_Kong",
  TW: "Asia/Taipei",
  JP: "Asia/Tokyo",
  KR: "Asia/Seoul",
  MN: "Asia/Ulaanbaatar",
  // Middle East / West Asia
  AE: "Asia/Dubai",
  SA: "Asia/Riyadh",
  QA: "Asia/Qatar",
  KW: "Asia/Kuwait",
  BH: "Asia/Bahrain",
  OM: "Asia/Muscat",
  IR: "Asia/Tehran",
  IQ: "Asia/Baghdad",
  IL: "Asia/Jerusalem",
  JO: "Asia/Amman",
  LB: "Asia/Beirut",
  SY: "Asia/Damascus",
  TR: "Europe/Istanbul",
  YE: "Asia/Aden",
  // Central Asia / Caucasus
  KZ: "Asia/Almaty",
  UZ: "Asia/Tashkent",
  AZ: "Asia/Baku",
  GE: "Asia/Tbilisi",
  AM: "Asia/Yerevan",
  // Europe
  GB: "Europe/London",
  IE: "Europe/Dublin",
  PT: "Europe/Lisbon",
  ES: "Europe/Madrid",
  FR: "Europe/Paris",
  DE: "Europe/Berlin",
  IT: "Europe/Rome",
  NL: "Europe/Amsterdam",
  BE: "Europe/Brussels",
  CH: "Europe/Zurich",
  AT: "Europe/Vienna",
  PL: "Europe/Warsaw",
  CZ: "Europe/Prague",
  SK: "Europe/Bratislava",
  HU: "Europe/Budapest",
  RO: "Europe/Bucharest",
  BG: "Europe/Sofia",
  GR: "Europe/Athens",
  SE: "Europe/Stockholm",
  NO: "Europe/Oslo",
  DK: "Europe/Copenhagen",
  FI: "Europe/Helsinki",
  UA: "Europe/Kyiv",
  RU: "Europe/Moscow",
  BY: "Europe/Minsk",
  RS: "Europe/Belgrade",
  HR: "Europe/Zagreb",
  // Africa
  NG: "Africa/Lagos",
  GH: "Africa/Accra",
  KE: "Africa/Nairobi",
  ZA: "Africa/Johannesburg",
  EG: "Africa/Cairo",
  MA: "Africa/Casablanca",
  DZ: "Africa/Algiers",
  TN: "Africa/Tunis",
  ET: "Africa/Addis_Ababa",
  TZ: "Africa/Dar_es_Salaam",
  UG: "Africa/Kampala",
  CM: "Africa/Douala",
  CI: "Africa/Abidjan",
  SN: "Africa/Dakar",
  // Americas
  US: "America/New_York",
  CA: "America/Toronto",
  MX: "America/Mexico_City",
  BR: "America/Sao_Paulo",
  AR: "America/Argentina/Buenos_Aires",
  CO: "America/Bogota",
  CL: "America/Santiago",
  PE: "America/Lima",
  VE: "America/Caracas",
  EC: "America/Guayaquil",
  BO: "America/La_Paz",
  PY: "America/Asuncion",
  UY: "America/Montevideo",
  GT: "America/Guatemala",
  DO: "America/Santo_Domingo",
  // Oceania
  AU: "Australia/Sydney",
  NZ: "Pacific/Auckland",
  FJ: "Pacific/Fiji",
  PG: "Pacific/Port_Moresby",
};

/** Timezone for an ISO2 country code, or undefined if unmapped. */
export function timezoneForCountry(iso2?: string | null): string | undefined {
  if (!iso2) return undefined;
  return COUNTRY_TZ[iso2.toUpperCase()];
}
