CREATE TABLE IF NOT EXISTS "GameCategory" ("id" TEXT NOT NULL, "slug" TEXT NOT NULL, "name" TEXT NOT NULL, "iconKey" TEXT, "color" TEXT, "order" INTEGER NOT NULL DEFAULT 0, "isActive" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "GameCategory_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX IF NOT EXISTS "GameCategory_slug_key" ON "GameCategory"("slug");
CREATE INDEX IF NOT EXISTS "GameCategory_isActive_order_idx" ON "GameCategory"("isActive", "order");
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "categoryId" TEXT;
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "coverUrl" TEXT;
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "isFeatured" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "orientation" TEXT NOT NULL DEFAULT 'ANY';
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "embedProbe" JSONB;
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "adsEnabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "adOnOpen" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "adOnResume" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "adOnQuit" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "adIntervalSeconds" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "adThrottleSeconds" INTEGER NOT NULL DEFAULT 60;
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "adPlacement" TEXT NOT NULL DEFAULT 'GAME_INTERSTITIAL';
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "rewardEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "rewardPointsPerTick" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "rewardTickSeconds" INTEGER NOT NULL DEFAULT 60;
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "rewardMaxPerSession" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "rewardDailyCapPoints" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "rewardRequiresAd" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "scoreRewardEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "scoreTrusted" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "scorePointsPer1000" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "scoreDailyCapPoints" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "uniquePlayersCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "totalPlaySeconds" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "adsShownCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Game" ADD COLUMN IF NOT EXISTS "pointsAwardedTotal" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Game" ADD CONSTRAINT "Game_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "GameCategory"("id") ON DELETE SET NULL ON UPDATE CASCADE;
CREATE TABLE IF NOT EXISTS "GameSession" ("id" TEXT NOT NULL, "gameId" TEXT NOT NULL, "userId" TEXT NOT NULL, "startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "lastBeatAt" TIMESTAMP(3), "endedAt" TIMESTAMP(3), "playedSeconds" INTEGER NOT NULL DEFAULT 0, "creditedSeconds" INTEGER NOT NULL DEFAULT 0, "pointsAwarded" INTEGER NOT NULL DEFAULT 0, "adsShown" INTEGER NOT NULL DEFAULT 0, "score" INTEGER, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "GameSession_pkey" PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "GameSession_gameId_startedAt_idx" ON "GameSession"("gameId", "startedAt");
CREATE INDEX IF NOT EXISTS "GameSession_userId_startedAt_idx" ON "GameSession"("userId", "startedAt");
CREATE INDEX IF NOT EXISTS "GameSession_userId_endedAt_idx" ON "GameSession"("userId", "endedAt");
ALTER TABLE "GameSession" ADD CONSTRAINT "GameSession_gameId_fkey" FOREIGN KEY ("gameId") REFERENCES "Game"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE TABLE IF NOT EXISTS "GameEarnLog" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "gameId" TEXT NOT NULL, "sessionId" TEXT, "points" INTEGER NOT NULL DEFAULT 0, "kind" TEXT NOT NULL DEFAULT 'TIME', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "GameEarnLog_pkey" PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "GameEarnLog_userId_createdAt_idx" ON "GameEarnLog"("userId", "createdAt");
CREATE INDEX IF NOT EXISTS "GameEarnLog_userId_gameId_createdAt_idx" ON "GameEarnLog"("userId", "gameId", "createdAt");
CREATE INDEX IF NOT EXISTS "GameEarnLog_gameId_createdAt_idx" ON "GameEarnLog"("gameId", "createdAt");
INSERT INTO "GameCategory" ("id", "name", "slug", "order", "createdAt", "updatedAt") SELECT gen_random_uuid()::text, s.category, lower(regexp_replace(trim(s.category), '[^a-zA-Z0-9]+', '-', 'g')), 0, now(), now() FROM (SELECT DISTINCT trim(category) AS category FROM "Game" WHERE category IS NOT NULL AND trim(category) <> '') s ON CONFLICT ("slug") DO NOTHING;
UPDATE "Game" g SET "categoryId" = c.id FROM "GameCategory" c WHERE g."categoryId" IS NULL AND g.category IS NOT NULL AND lower(trim(g.category)) = lower(c.name);
CREATE INDEX CONCURRENTLY IF NOT EXISTS "Game_isFeatured_order_idx" ON "Game"("isFeatured", "order");
CREATE INDEX CONCURRENTLY IF NOT EXISTS "Game_categoryId_isActive_order_idx" ON "Game"("categoryId", "isActive", "order");
