ALTER TABLE "UserDevice" ADD COLUMN IF NOT EXISTS "deviceType" TEXT;
ALTER TABLE "UserDevice" ADD COLUMN IF NOT EXISTS "os" TEXT;
ALTER TABLE "UserDevice" ADD COLUMN IF NOT EXISTS "osVersion" TEXT;
ALTER TABLE "UserDevice" ADD COLUMN IF NOT EXISTS "brand" TEXT;
ALTER TABLE "UserDevice" ADD COLUMN IF NOT EXISTS "model" TEXT;
ALTER TABLE "UserDevice" ADD COLUMN IF NOT EXISTS "browser" TEXT;
CREATE INDEX IF NOT EXISTS "UserDevice_deviceType_idx" ON "UserDevice"("deviceType");
CREATE INDEX IF NOT EXISTS "UserDevice_os_idx" ON "UserDevice"("os");
CREATE INDEX IF NOT EXISTS "UserDevice_brand_idx" ON "UserDevice"("brand");

ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "deviceTypes" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "deviceOses" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "deviceBrands" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Banner" ADD COLUMN IF NOT EXISTS "deviceTypes" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Banner" ADD COLUMN IF NOT EXISTS "deviceOses" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Banner" ADD COLUMN IF NOT EXISTS "deviceBrands" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "SitePopup" ADD COLUMN IF NOT EXISTS "deviceTypes" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "SitePopup" ADD COLUMN IF NOT EXISTS "deviceOses" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "SitePopup" ADD COLUMN IF NOT EXISTS "deviceBrands" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
