ALTER TABLE "Banner" ADD COLUMN IF NOT EXISTS "planAudience" TEXT NOT NULL DEFAULT 'ANY';
ALTER TABLE "Banner" ADD COLUMN IF NOT EXISTS "packageIds" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Banner" ADD COLUMN IF NOT EXISTS "minLevel" INTEGER;
ALTER TABLE "Banner" ADD COLUMN IF NOT EXISTS "maxLevel" INTEGER;
ALTER TABLE "Banner" ADD COLUMN IF NOT EXISTS "minAccountDays" INTEGER;
ALTER TABLE "Banner" ADD COLUMN IF NOT EXISTS "maxAccountDays" INTEGER;
