CREATE TYPE "LotteryPrizeMode" AS ENUM ('FIXED', 'POOL');
CREATE TYPE "LotteryShortfallAction" AS ENUM ('DRAW', 'REFUND', 'ROLLOVER');
CREATE TYPE "LotteryOutcome" AS ENUM ('DRAWN', 'REFUNDED', 'ROLLED_OVER', 'VOID_NO_TICKETS');
ALTER TABLE "Lottery" ADD COLUMN IF NOT EXISTS "prizeMode" "LotteryPrizeMode" NOT NULL DEFAULT 'FIXED';
ALTER TABLE "Lottery" ADD COLUMN IF NOT EXISTS "prizeTiers" JSONB;
ALTER TABLE "Lottery" ADD COLUMN IF NOT EXISTS "houseCutPercent" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Lottery" ADD COLUMN IF NOT EXISTS "poolSeedPoints" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Lottery" ADD COLUMN IF NOT EXISTS "poolCapPoints" INTEGER;
ALTER TABLE "Lottery" ADD COLUMN IF NOT EXISTS "minTickets" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Lottery" ADD COLUMN IF NOT EXISTS "shortfallAction" "LotteryShortfallAction" NOT NULL DEFAULT 'DRAW';
ALTER TABLE "Lottery" ADD COLUMN IF NOT EXISTS "rolloverTargetId" TEXT;
ALTER TABLE "Lottery" ADD COLUMN IF NOT EXISTS "rolloverInPoints" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Lottery" ADD COLUMN IF NOT EXISTS "rolloverFromId" TEXT;
CREATE TABLE IF NOT EXISTS "LotterySettlement" ("id" TEXT NOT NULL, "lotteryId" TEXT NOT NULL, "outcome" "LotteryOutcome" NOT NULL, "prizeMode" "LotteryPrizeMode" NOT NULL, "ticketsSold" INTEGER NOT NULL, "ticketPrice" INTEGER NOT NULL, "grossSalesPoints" INTEGER NOT NULL DEFAULT 0, "houseCutPercent" INTEGER NOT NULL DEFAULT 0, "houseCutPoints" INTEGER NOT NULL DEFAULT 0, "seedPoints" INTEGER NOT NULL DEFAULT 0, "rolloverInPoints" INTEGER NOT NULL DEFAULT 0, "prizePoolPoints" INTEGER NOT NULL DEFAULT 0, "paidOutPoints" INTEGER NOT NULL DEFAULT 0, "refundedPoints" INTEGER NOT NULL DEFAULT 0, "rolledOverPoints" INTEGER NOT NULL DEFAULT 0, "overflowToHouse" INTEGER NOT NULL DEFAULT 0, "rolloverToId" TEXT, "tiers" JSONB, "winners" JSONB, "drawOrderHash" TEXT, "settledAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "LotterySettlement_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX IF NOT EXISTS "LotterySettlement_lotteryId_key" ON "LotterySettlement"("lotteryId");
CREATE INDEX IF NOT EXISTS "LotterySettlement_outcome_settledAt_idx" ON "LotterySettlement"("outcome", "settledAt");
CREATE INDEX IF NOT EXISTS "LotterySettlement_rolloverToId_idx" ON "LotterySettlement"("rolloverToId");
ALTER TABLE "LotterySettlement" ADD CONSTRAINT "LotterySettlement_lotteryId_fkey" FOREIGN KEY ("lotteryId") REFERENCES "Lottery"("id") ON DELETE CASCADE ON UPDATE CASCADE;
CREATE INDEX CONCURRENTLY IF NOT EXISTS "Lottery_status_drawDate_idx" ON "Lottery"("status", "drawDate");
