ALTER TABLE "TaskBoard" ADD COLUMN IF NOT EXISTS "startsAt" TIMESTAMP(3);
ALTER TABLE "TaskBoard" ADD COLUMN IF NOT EXISTS "kycAudience" TEXT NOT NULL DEFAULT 'ANY';
ALTER TABLE "TaskBoard" ADD COLUMN IF NOT EXISTS "deviceTypes" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "TaskBoard" ADD COLUMN IF NOT EXISTS "deviceOses" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "TaskBoard" ADD COLUMN IF NOT EXISTS "deviceBrands" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
